---
---

<br>

### Publications

<br>

[__Curating Local Knowledge: Experimental Evidence from Small Retailers in Indonesia__](https://academic.oup.com/jeea/advance-article/doi/10.1093/jeea/jvab007/6134759)

with [Patricio S. Dalton](https://sites.google.com/site/psdalton), [Burak Uras](https://sites.google.com/site/burakruras), and [Bilal Zia](https://sites.google.com/site/decbilalzia)

**Journal of the European Economic Association, Volume 19, Issue 5, October 2021**

<details>
<summary>Abstract</summary>

> <sub>Business practices and performance vary widely among local peers. This paper identifies key determinants of such heterogeneity among a sample of small urban retail shops in Indonesia, and experimentally tests whether learning about the best practices of local peers is valuable for business growth. Through extensive baseline quantitative and qualitative fieldwork, the study develops a handbook that associates specific business practices with performance and provides detailed implementation guidance informed by exemplary local shop owners. Instead of offering formal training or in-depth counseling, this handbook is simply distributed to a randomly selected sample of shop owners and complemented with three experiential learning modules: one group is invited to watch a documentary video on experiences of highly successful peers, another is offered light in-shop assistance on the implementation of the hand-book, and a third group is offered both. Eighteen months after the intervention, the study finds no effect of offering the handbook alone, but significant impact on practice adoption when the handbook is coupled with experiential learning. On business performance, the study finds sizable and significant improvements as well, up to an increase of 35 percent in profits and an increase of 16.7 percent in revenues. The types of practices adopted map these performance improvements to efficiency gains rather than other channels. The analysis suggests that these interventions are simple, scalable, and highly cost-effective.</sub>

</details>

<p>

<sup> Material: [Documentary of successful peers](https://www.youtube.com/watch?v=7kNz0k7-y4E&feature=youtu.be), <a href="files/LearningFromPeers_Handbook.pdf" class="image fit">Handbook of local best practices</a>

<sup> Coverage: [VoxDevLit](https://voxdev.org/lits/training-entrepreneurs), [Development Impact](https://blogs.worldbank.org/impactevaluations/learning-other-firms-entrepreneur-never-meets), [Nesta](https://www.nesta.org.uk/blog/dont-overlook-local-skills-effective-policies-improve-business-practice/)

<br>

[__Worries of the Poor: The Impact of Financial Burden on the Risk Attitudes of Micro-entrepreneurs__](https://www.sciencedirect.com/science/article/pii/S016748701830727X)

with [Patricio S. Dalton](https://sites.google.com/site/psdalton/) and Nhung Nguyen

**Journal of Economic Psychology, Volume 79, August 2020**


<details>
<summary>Abstract</summary>

> <sub>We randomly expose the owners of small retail businesses in Vietnam to scenarios that trigger financial worries and study the effect of this intervention on risk attitudes. Using an incentive-compatible investment game, we ﬁnd that entrepreneurs exposed to financial worries are more likely to seek ﬁnancial risks than those assigned to a placebo treatment. In line with psychological theory on the effect of affective states and stress on risk-taking behavior, this effect is stronger for owners of shops which are smaller and less exposed to large income shocks in their everyday business. We further show that the effect of financial worries on risk attitudes is not explained by changes in the cognitive functioning of the treated. The findings point to the crucial role of financial worries in economic decision-making under poverty.</sub>

</details>

<p>

<sup> Material: [Replication file and data](https://www.sciencedirect.com/science/article/pii/S016748701830727X#ec-research-data)

<br>
<br>




### Working Papers

<br>

[__Unconditional Cash Transfers: A Bayesian Meta-Analysis of Randomized Evaluations in Low and Middle Income Countries__](https://www.nber.org/papers/w32779)

with [Tommaso Crosta](https://tommaso11397.github.io/Personal-Website/), [Dean Karlan](http://deankarlan.com/), [Finley Ong](https://www.linkedin.com/in/finley-ong-2818b617a/), and [Chris Udry](https://sites.northwestern.edu/christopherudry/)

*NBER Working Paper*

<details>
<summary>**Abstract**</summary>

> <sub>We use Bayesian meta-analysis methods to estimate the impact of unconditional cash transfers (UCTs) on twelve primary outcomes from 114 studies of 72 UCT programs in middle and low income countries. Cash transfers generate strong and positive average treatment effects on ten of thirteen outcomes: monthly household total and food consumption, monthly income, labor supply, school enrollment, food security, psychological well-being, total assets, financial assets, and children height-for-age. The three remaining outcomes have prediction intervals mostly positive, but that include zero: number of hours worked, children weight-for-age, and stunting. We draw six conclusions: First, consistent with several models of capital market failures, households consume more of streams and invest more of lump sums, however once stream programs end the impacts mirror those of lump sum, indicating some propensity to save a portion of stream transfers. Second, long-run treatment effects remain broadly strong, with some evidence of lump sums modestly dissipating impact while ongoing streams augmenting impact. Third, returns are linear or slightly negative with respect to grant amount, thus we do not find evidence for threshold-based poverty traps within the observed range of transfers and with this study-level analytical method. Fourth, effects on consumption and income are greater for UCTs targeted to women. Fifth, programs employing light-touch framing related to child welfare or food security have weakly stronger impacts. Sixth, positive impacts on labor supply and income suggest no evidence of “dependency” theories that cash transfers demotivate income-generating activity on average.</sub>

</details>

<p>

<br>


[__Determinants and Dynamics of Business Aspirations: Evidence from Small-scale Entrepreneurs in an Emerging Market__](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3128196)

with [Patricio S. Dalton](https://sites.google.com/site/psdalton/research) and [Bilal Zia](https://sites.google.com/site/decbilalzia/home)

*SSRN Working Paper*

<details>
<summary>**Abstract**</summary>

> <sub>Small-scale entrepreneurs are ubiquitous in emerging market economies, yet very few graduate to become larger businesses. We ask whether such entrepreneurs even aspire to grow, and if so, on which dimensions of the business? What factors inﬂuence these aspirations, how realistic are they, and do entrepreneurs dynamically update them based on realized outcomes? Using a unique panel data set of small-scale retailers in Indonesia, we show that the average business has strong short- and long-term aspirations for growth in shop size, number of employees, number of customers, and sales. Yet, more than half of the businesses report no aspirations for growth in the next 12 months, and 16 percent fail to imagine an ideal business over the long-term. Entrepreneurs with low proﬁts, business skills, and agency beliefs, as well as those who are older, female, and less educated have significantly lower aspirations. Analysis from a year later shows that most entrepreneurs fail to set realistic aspirations at baseline, but significantly adjust their aspirations to realistic levels with realized outcomes. The analysis also shows baseline aspirations are a strong predictor of measures of business expansion and innovation, as well as performance outcomes a year later.</sub>

</details>

<p>

<sup> **Coverage**: [Let's Talk Development](http://blogs.worldbank.org/developmenttalk/what-are-business-aspirations-worth-developing-countries)



