---
---

<br>

### Teaching

<br>

**U.C. Berkeley**

* [Lec] International Economic Development Policy
  + For Postgraduates in Public Policy and Agricultural Economics
  + Sessions on Credit Markets, Microcredit, and Firms  

<br>

* [WS] <a href="https://cega.berkeley.edu/initiative/diwa/" target="_blank">DIWA Impact Evaluation Training</a>
  + For Researchers and Policy Makers from West Africa (Participants of DIWA) 
  
<br>

* [WS] Machine Learning for Development Economics (<a href="files/Intro-ML.html" target="_blank">Introductory Slides</a>)

<br>

* [WS] Short tutorial on Aspirations Theory (<a href="files/aspTheory.html" target="_blank">Slides</a>)



<br>

**Tilburg University**

* [TA] Advancing Society: Markets, Games, & Behavior (Behavioral Econ; 2018)
  + For Undergraduates in Business

<br>

* [TA & Lec] Introduction to Development Economics (2017, 2018)
  + For Undergraduates in Economics and Business
  + [Lec] Econometrics Lab (Data preparation and analysis in Stata)

<br>

**Bielefeld Unversity**               

* [TA] Introductory Statistics for Psychology (2010)

<br>
<br>


### Thesis Supervision

<br>

**Tilburg University**

* Undergraduate Theses in Economics and Social Science



